HuntingFishGame.H5/Controllers/AlipayController.cs
using Aop.Api.Util;
using BSF.SystemConfig;
using HuntingFishGame.H5.Models;
using HuntingFishGame.H5.Models.AlipayCommon;
using HuntingFishGame.H5.Models.WeChatCommon;
using HuntingFishGame.ManageDomain.BLL.GoldShopOrder;
using HuntingFishGame.ManageDomain.Model.GoldShopOrder;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HuntingFishGame.H5.Controllers
{
    public class AlipayController : Controller
    {
        public ActionResult OrderPayRequest(string orderId, string toUrl)
        {
            ViewBag.orderId = orderId;
            //JSAPI支付预处理
            return View();
        }

        public JsonResult GetAlipayData(string orderId)
        {
            string alipayData = AlipayCore.GetAlipayData(orderId);
            return Json(new { alipayData = alipayData });
        }

        public string AlipayNotify()
        {
            BSF.Log.CommLog.Write("CallBack" + DateTime.Now);

            SortedDictionary<string, string> para = null;
            SortedDictionary<string, string> para2 = null;
            try
            {
                para = PaymentCommon.GetRequestPost(this);
                para2 = PaymentCommon.GetRequestPost(this);
                //para2 = PaymentCommon.GetRequestPost(this);
                BSF.Log.CommLog.Write(Newtonsoft.Json.JsonConvert.SerializeObject(para));
                Notify notify = new Notify();
                string signContent = AlipaySignature.GetSignContent(para);
                //这个是新版本的验证签名
                BSF.Log.CommLog.Write("check111:" );
                //这个是旧版本的方法
                if (AlipaySignature.RSACheckV1(para, AlipayConfig.alipay_public_key, AlipayConfig.input_charset, AlipayConfig.sign_type, false))//notify.Verify(para2, Request.Form["notify_id"], Request.Form["sign"]))
                {
                    BSF.Log.CommLog.Write("1");
                    if (para["trade_status"] == "TRADE_SUCCESS" || para["trade_status"] == "TRADE_FINISHED")
                    {
                        BSF.Log.CommLog.Write("2");
                        string tid = (para["out_trade_no"]).ToString();
                        bool isSend = GoldShopOrderBLL.GetPayStatus(BSFConfig.MainConnectString, tid);//是否已推送公众号提醒
                        BSF.Log.CommLog.Write("3");
                        if (!isSend)
                        {
                            BSF.Log.CommLog.Write("4");
                            GoldShopOrderModel payModel = new GoldShopOrderModel()
                            {
                                orderid = tid.ToString(),
                                payment_time = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),
                                payment_number = para["buyer_id"].ToString(),
                                payment_orderid = para["trade_no"].ToString(),
                                payment_status = "1",
                                payment_type = "1"
                            };

                            bool respay = GoldShopOrderBLL.Update(BSFConfig.MainConnectString, payModel);
                            BSF.Log.CommLog.Write("5：" + respay);
                            if (!respay)
                            {
                                //业务数据处理失败
                                return "failed";
                            }
                            else
                            {
                                //公众号消息推送(只推送已关注公众号的用户)
                                //XXF.Log.CommLog.Write("商品名称字符集合：" + spmcstr);
                                if (!string.IsNullOrEmpty(""))
                                {
                                    //推送成功消息
                                }
                            }
                        }
                        return "success";
                    }
                    else
                    {
                        return "failed";
                    }
                    //正常，写数据
                }
                else
                {
                    throw new Exception("失败！");
                }
            }
            catch (Exception ex)
            {
                BSF.Log.ErrorLog.Write(ex.Message, ex);
                Console.WriteLine(ex.Message);
                return "failed";
                //throw new Exception("服务器出错" + ex.Message);
            }
        }
    }
}

HuntingFishGame.H5/Controllers/GoldShopOrderController.cs
using HuntingFishGame.H5.Models;
using HuntingFishGame.ManageDomain.BLL.GoldShopGoods;
using HuntingFishGame.ManageDomain.Model.GoldShopGoods;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BSF.SystemConfig;
using HuntingFishGame.ManageDomain.Model.GoldShopOrder;
using HuntingFishGame.ManageDomain.BLL.GoldShopOrder;

namespace HuntingFishGame.H5.Controllers
{
    public class GoldShopOrderController : Controller
    {
        public ActionResult CreateOrder(long id, string openid)
        {
            GoldShopGoodsModel goodModel = GoldShopGoodsBLL.GetInfo(BSFConfig.MainConnectString, id);

            DateTime nowDate = DateTime.Now;
            if (Convert.ToDateTime(goodModel.starttime) <= nowDate && Convert.ToDateTime(goodModel.endtime) >= nowDate)
            {
                Random ran = new Random();
                int RandKey = ran.Next(100, 999);
                GoldShopOrderModel model = new GoldShopOrderModel();
                model.gid = goodModel.id.ToString();
                model.gift_gold = goodModel.giftgold;
                model.create_time = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
                model.gold = goodModel.gold;
                model.openid = openid;
                model.orderid = DateTime.Now.ToString("yyyyMMdd") + model.openid.GetHashCode().ToString() + RandKey;
                model.payment_status = "0";
                model.price = goodModel.price;
                model.text = goodModel.text;
                model.userid = "";
                bool check = GoldShopOrderBLL.Add(BSFConfig.MainConnectString, model);
                if (check)
                {
                    return Json(new { code = 1, msg = "success", orderId = model.orderid });
                }
                else
                {
                    return Json(new { code = -1, msg = "生成订单失败！" });
                }
            }
            else
            {
                return Json(new { code = -1, msg = "购买商品已过期！" });
            }
        }

        public ActionResult PaymentPage(string orderId, string openid)
        {
            ViewBag.openid = openid;
            GoldShopOrderModel orderModel = GoldShopOrderBLL.GetInfo(BSFConfig.MainConnectString, orderId);
            return View(orderModel);
        }

        public ActionResult PaymentError()
        {
            return View();
        }

        public ActionResult PaymentSuccess()
        {
            return View();
        }
    }
}

HuntingFishGame.H5/Views/GoldShopOrder/PaymentError.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
<title>充值中心</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Cache-Control" content="no-cache" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=2.0,user-scalable=no" />
</head>
<body>
<div class="resultBox">
	<dl>
		<dt>
			<img src="~/image/error.png" />
		</dt>
		<dd class="gray">支付失败</dd>
	</dl>

</div>
	<a href="/goldshopgoods/index" class="link">前往继续充值</a>
    <script src="~/Scripts/main.js"></script>
</body>

HuntingFishGame.H5/Views/GoldShopOrder/PaymentPage.cshtml
@using HuntingFishGame.ManageDomain.Model.GoldShopOrder;
@model GoldShopOrderModel
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/mui.min.css" rel="stylesheet" />
    <script src="~/Scripts/mui.min.js"></script>
    <script src="~/Scripts/jQuery.min.js"></script>
    <title>支付平台</title>
    <script type="text/JavaScript">
        $(function () {
            var alipay = document.getElementById("alipay");
            alipay.addEventListener("tap", function () {
                var text = $("#text").html();
                var amount = $("#amount").html();
                var url = "@Url.Action("GetAlipayData", "Alipay")";
                $.post(url,
                    {
                        orderId:$("#orderId").val(),
                        text: text,
                        amount: amount,
                    }, function (data) {
                        if (data != "") {
                            $("#formDiv").append(data.alipayData);
                            $("#alipaysubmit").submit();
                        }
                    });
            });
            var wxpay = document.getElementById("wxpay");
            wxpay.addEventListener("tap", function () {
                window.location.href="/WeChat/OrderPayRequest?orderId="+$("#orderId").val()+"&toUrl='/GoldShopOrder/PaymentSuccess'&openid=@ViewBag.openid";
            });
        });
    </script>
</head>
<body>
    <div>
        <header class="mui-bar mui-bar-nav">
            <a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
            <h1 class="mui-title">选择支付方式</h1>
        </header>
        <!--Infomations-->
        <div class="mui-content">
            <div class="mui-card">
                <input type="hidden" id="orderId" value="@Model.orderid" />
                <ul class="mui-table-view">
                    <li class="mui-table-view-cell">商品名称：<span id="text">@Model.text</span>
                    </li>
                    <li class="mui-table-view-cell">商品单价：<span id="amount">@Model.price</span>
                    </li>
                </ul>
            </div>
            <div style="color: red; margin: 10px; font-size: 14px;">订单有效时间：30分钟</div>
            <div class="mui-card">
                <ul class="mui-table-view">
                    <li id="alipay" class="mui-table-view-cell">
                        <a class="mui-navigate-right">支付宝
                        </a>
                    </li>
                    <li id="wxpay" class="mui-table-view-cell">
                        <a class="mui-navigate-right">微信
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!--form-->
        <div id="formDiv" style="display: none;">
        </div>
    </div>
</body>
</html>

HuntingFishGame.H5/Views/GoldShopOrder/PaymentSuccess.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<title>充值中心</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Cache-Control" content="no-cache" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=2.0,user-scalable=no" />
</head>
<body>
    <div class="resultBox">
        <dl>
            <dt>
                <img src="~/image/success.png" />
            </dt>
            <dd>支付完成</dd>
        </dl>
    </div>
    <a href="/goldshopgoods/index" class="link">前往继续充值</a>
    <script src="~/Scripts/main.js"></script>
</body>