HuntingFishGame.Manage/Controllers/AutoReplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using BSF.Db;
using BSF.Enums;
using BSF.SystemConfig;
using HuntingFishGame.ManageDomain.BLL.WeChat;
using HuntingFishGame.ManageDomain.Model.WeChat;
using Webdiyer.WebControls.Mvc;

namespace HuntingFishGame.Manage.Controllers
{
    public class AutoReplyController : Controller
    {
        //
        // GET: /ProgramMain/
        public ActionResult Index(string keyword, bool? sfdj, string CStime, string CEtime, int pageIndex = 1, int pageSize = 10)
        {
            ViewBag.sfdj = sfdj;
            ViewBag.keyword = keyword;
            ViewBag.CStime = CStime;
            ViewBag.CEtime = CEtime;
            ViewBag.pageIndex = pageIndex;
            ViewBag.pageSize = pageSize;

            PagedList<AutoReplyModel> pageList = null;
            int count = 0;
            DateTime? stime = null;
            if (!string.IsNullOrWhiteSpace(CStime))
            {
                stime = LibConvert.ObjToDateTime(CStime);
            }
            DateTime? etime = null;
            if (!string.IsNullOrWhiteSpace(CEtime))
            {
                etime = LibConvert.ObjToDateTime(CEtime);
            }
            List<AutoReplyModel> list = AutoReplyBLL.GetList(BSFConfig.MainConnectString, sfdj, stime, etime, keyword, "", out count, pageIndex, pageSize);
            pageList = new PagedList<AutoReplyModel>(list, pageIndex, pageSize, count);

            Dictionary<string, string> dict = new Dictionary<string, string>();
            dict.Add("true", "是");
            dict.Add("false", "否");
            ViewBag.StateList = dict;
            return View(pageList);
        }

        public ActionResult AddOrEdit(long id = 0, bool? sfdj = null)
        {
            ViewBag.sfdj = sfdj;
            Dictionary<string, string> dict = new Dictionary<string, string>();
            dict.Add("true", "是");
            dict.Add("false", "否");
            ViewBag.StateList = dict;
            if (id == 0)
            {
                return View(new AutoReplyModel());
            }
            else
            {
                AutoReplyModel model = AutoReplyBLL.GetInfo(BSFConfig.MainConnectString, id);
                return View(model);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddOrEdit(AutoReplyModel model)
        {
            //return Json(new { code = (int)BSFAPICode.NormalError, msg = "已存在重复的关键词" });
            if (model.id == 0)
            {
                //判断是否有重复的关键词
                if (AutoReplyBLL.Exists(BSFConfig.MainConnectString, model.keyword))
                {
                    return Json(new { code = (int)BSFAPICode.NormalError, msg = "已存在重复的关键词" });
                    //return Content("已存在重复的关键词");
                }
            }
            else
            {
                //判断是否有重复的关键词
                if (AutoReplyBLL.Exists(BSFConfig.MainConnectString, model.keyword, model.id))
                {
                    return Json(new { code = (int)BSFAPICode.NormalError, msg = "已存在重复的关键词" });
                }
            }
            model.jdrbm = "";
            model.jdrmc = "";
            model.createtime = DateTime.Now;
            bool state = model.id == 0 ? AutoReplyBLL.Add(BSFConfig.MainConnectString, model) : AutoReplyBLL.Update(BSFConfig.MainConnectString, model);
            return Json(new { code = (int)BSFAPICode.Success, msg = "成功", ReturnUrl = SiteUrls.Instance().AutoReplyListUrl() });
            //return RedirectToAction("index");
        }

        public JsonResult UpdateState(long id, bool sfdj)
        {
            bool result = AutoReplyBLL.UpdateState(BSFConfig.MainConnectString, id, sfdj);
            return Json(new { code = 1, Data = result });
        }

        public JsonResult Delete(long id)
        {
            bool result = AutoReplyBLL.Delete(BSFConfig.MainConnectString, id);
            return Json(new { code = 1, Data = result });
        }
    }
}

HuntingFishGame.Manage/Controllers/GoldShopGoodsController.cs
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using HuntingFishGame.ManageDomain.BLL;
using HuntingFishGame.ManageDomain.Model.GoldShopGoods;
using HuntingFishGame.ManageDomain.BLL.GoldShopGoods;
using System.Collections.Generic;
using BSF.SystemConfig;

namespace Dyd.BaseService.ConfigManager.Web.Controllers
{
    public class GoldShopGoodsController : Controller
    {
        //
        // GET: /ProgramMain/
        public ActionResult Index()
        {
            List<GoldShopGoodsModel> pageList = null;
            int count = 0;
            List<GoldShopGoodsModel> List = GoldShopGoodsBLL.GetList(BSFConfig.MainConnectString, false);
            return View(List);
        }

        public ActionResult AddOrEdit(long id = 0)
        {
            if (id == 0)
            {
                return View(new GoldShopGoodsModel());
            }
            else
            {
                GoldShopGoodsModel model = GoldShopGoodsBLL.GetInfo(BSFConfig.MainConnectString, id);
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(GoldShopGoodsModel model)
        {
            bool state = model.id == 0 ? GoldShopGoodsBLL.Add(BSFConfig.MainConnectString, model) : GoldShopGoodsBLL.Update(BSFConfig.MainConnectString, model);
            return RedirectToAction("index");
        }

        public JsonResult Delete(long id)
        {
            bool state = GoldShopGoodsBLL.Delete(BSFConfig.MainConnectString, id);
            return Json(new { code = 1, Data = state });
        }
    }
}

HuntingFishGame.Manage/Controllers/GoldShopOrderController.cs
using System.Web.Mvc;
using System.Collections.Generic;
using BSF.SystemConfig;
using HuntingFishGame.ManageDomain.Model.GoldShopOrder;
using HuntingFishGame.ManageDomain.BLL.GoldShopOrder;
using Webdiyer.WebControls.Mvc;

namespace Dyd.BaseService.ConfigManager.Web.Controllers
{
    public class GoldShopOrderController : Controller
    {
        //
        // GET: /ProgramMain/
        public ActionResult Index(int pageIndex = 0, int pageSize = 0)
        {
            PagedList<GoldShopOrderModel> pageList = null;
            int count = 0;
            List<GoldShopOrderModel> list = GoldShopOrderBLL.GetList(BSFConfig.MainConnectString, pageIndex, pageSize, out count);
            pageList = new PagedList<GoldShopOrderModel>(list, pageIndex, pageSize, count);
            return View(pageList);
        }
    }
}

HuntingFishGame.Manage/Views/Shared/Success.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
</head>
<body>
<div>
    成功
</div>
</body>
</html>

HuntingFishGame.Manage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>自动发布平台测试</title>
    <script src="@Url.Content("~/Scripts/jquery-1.8.3.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/JavaScript"></script>
    <link href="~/Content/css/css.css" rel="stylesheet" />
    <script src="~/Scripts/DatePicker/WdatePicker.js"></script>
    <link href="~/Scripts/Dialog/dialog.css" rel="stylesheet" />
    <script src="~/Scripts/Dialog/dialog.js"></script>
</head>
<body>
    <div class="header">
        <span style="color: white; font-size: 25px; margin-left: 25px; font-family: 微软雅黑; font-weight: bold;">自动发布平台</span>
    </div>
    <div class="content w">
        <div class="leftmenu fl">
            <ul class="level1">
                <li>
                    <p>项目管理<i></i></p>
                    <ul class="level2">
                        <li><a href="@Url.Action("Index", "AutoReply")">自动回复列表</a></li>
                        <li><a href="@Url.Action("Index", "GoldShopGoods")">金币商品列表</a></li>
                        <li><a href="@Url.Action("Index", "GoldShopOrder")">订单列表</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="main_cont">
            @RenderBody()
        </div>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>